name: CD for PR to Main

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          check-latest: true

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: '30.0.3'

      - name: Create local.properties
        env:
          SDK_DIR: ${{ secrets.SDK_DIR }}
          FEEDBACK_EMAIL: ${{ secrets.FEEDBACK_EMAIL }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        run: |
          echo "sdk.dir=${SDK_DIR}" > local.properties
          echo "feedback_email=${FEEDBACK_EMAIL}" >> local.properties
          echo "store_file=${{ github.workspace }}/app/keystore.jks" >> local.properties
          echo "store_password=${STORE_PASSWORD}" >> local.properties
          echo "key_password=${KEY_PASSWORD}" >> local.properties
          echo "key_alias=${KEY_ALIAS}" >> local.properties

      - name: Create google-services.json
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 -d > app/google-services.json

      - name: Create keystore.jks
        env:
          DATA: ${{ secrets.KEY_STORE }}
        run: echo $DATA | base64 -d > app/keystore.jks

      - name: Verify keystore file
        run: ls -la app/keystore.jks

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}

      - name: Clean Build
        run: ./gradlew clean

      - name: Build release AAB
        run: ./gradlew bundleRelease

      - name: Get version from build.gradle
        id: get_version
        run: |
          echo "VERSION_CODE=$(grep versionCode app/build.gradle.kts | sed 's/[^0-9]*//g')" >> $GITHUB_ENV
          echo "VERSION_NAME=$(grep versionName app/build.gradle.kts | sed 's/.*\"\([^\"]*\)\".*/\1/')" >> $GITHUB_ENV

      - name: Check if release exists
        id: check_release
        uses: actions/github-script@v6
        with:
          script: |
            const versionName = process.env.VERSION_NAME;
            const { data: releases } = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const releaseExists = releases.some(release => release.tag_name === `v${versionName}`);
            core.setOutput('releaseExists', releaseExists);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set release creation condition
        id: set_release_condition
        run: |
          echo "RELEASE_EXISTS=${{ steps.check_release.outputs.releaseExists }}" >> $GITHUB_ENV
          if [ "${{ steps.check_release.outputs.releaseExists }}" = "true" ]; then
            echo "RELEASE_EXISTS=true" >> $GITHUB_ENV
          else
            echo "RELEASE_EXISTS=false" >> $GITHUB_ENV
            echo "TAG_NAME=v${{ env.VERSION_NAME }}" >> $GITHUB_ENV
            echo "RELEASE_NAME=Release v${{ env.VERSION_NAME }}" >> $GITHUB_ENV
            echo "RELEASE_NOTE=Release notes for version ${{ env.VERSION_NAME }}" >> $GITHUB_ENV

      - name: Generate Release
        if: env.RELEASE_EXISTS == 'false'
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          body: ${{ env.RELEASE_NOTE }}
